### ISSUE TITLE
bug: regular search won't update label in other window when the pattern matchs nothing in current window

### ISSUE THREAD

**Issue by fjchen7** [folke/flash.nvim#44] opened 2023-06-24 02:27 UTC
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.2.1

### Describe the bug

In regular search mode, if the pattern matches nothing in current window, then it won't show the correct labels in others windows.

### Steps To Reproduce

<img width="740" alt="image" src="https://github.com/folke/flash.nvim/assets/10106636/6a3e8e31-46b5-4418-a67a-da9945345c88">

<img width="744" alt="image" src="https://github.com/folke/flash.nvim/assets/10106636/e18947bb-ab98-4611-8c36-aa53bbdb4f5b">

### Expected Behavior

Labels will be shown in other windows correctly even the pattern match nothing in current window.

### Repro

```Lua
{
  "folke/flash.nvim",
  event = "VeryLazy",
  keys = {
    {
      ";",
      mode = { "n", "x" },
      function()
        -- default options: exact mode, multi window, all directions, with a backdrop
        require("flash").jump()
      end,
      desc = "jump by multiple keys",
    },
    {
      "t",
      mode = { "n", "o", "x" },
      function()
        require("flash").treesitter()
      end,
      desc = "select by Treesitter node",
    },
    {
      "r",
      mode = "o",
      function()
        require("flash").remote()
      end,
      desc = "Remote Flash",
    },
  },
  opts = {
    modes = {
      char = {
        enabled = false,
      },
    }
  },
}
```

**Comment by folke** [comment] 2023-06-24 08:16
![image](https://github.com/folke/flash.nvim/assets/292349/bcc12207-231e-4876-9a5b-e3cd249bc437)

I'm not able to reproduce this.

Do you have `lazyredraw` or something similar enabled?

**Comment by fjchen7** [comment] 2023-06-24 09:31
My settings
- `lazyredraw`: off
- Not map `/`
- my current `flash.nvim`: 5e1096e

I have updated my flash configuration for repo, but it is nothing special. I am guessing it is due to conflict with other plugins. However I do not have any clues about this. 

I will update any findings once I have.

**Comment by folke** [comment] 2023-06-24 10:02
Closing this, since I can't reproduce it with a minimal `repro.lua`

**Closed by folke** 2023-06-24 10:02 UTC
Labels: bug
