### ISSUE TITLE
bug: Invoking Treesitter-mode throws multiple "invalid virt_text_pos" errors with default config

### ISSUE THREAD

**Issue by PeterPasdzierny** [folke/flash.nvim#111] opened 2023-07-01 21:09 UTC
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-36+g7ffe45017

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

(Minimal-) installing "flash.nvim" with default settings works fine, except for Treesitter-mode, which throws multiple "invalid virt_text_pos" errors on invocation (see screenshot below) and thus does not work at all.

![nvim_flash_error_01](https://github.com/folke/flash.nvim/assets/67273142/d954fe0c-1017-45bf-b9c9-dc7ee1fbeaf9)

### Steps To Reproduce

1. Type "s" to invoke jump-mode - this works fine!
2. Type "S" to invoke Treesitter-mode - this doesn't work and throws the above errors.

### Expected Behavior

Treesitter-mode working as intended.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/flash.nvim",
    keys = {
      {
        "s",
        mode = { "n", "x", "o" },
        function()
        require("flash").jump()
        end,
        desc = "Flash",
      },
      {
        "S",
        mode = { "n", "o", "x" },
        function()
        require("flash").treesitter()
        end,
        desc = "Flash Treesitter",
      },
      {
        "r",
        mode = "o",
        function()
        require("flash").remote()
        end,
        desc = "Remote Flash",
      },
      {
        "R",
        mode = { "o", "x" },
        function()
        require("flash").treesitter_search()
        end,
        desc = "Flash Treesitter Search",
      },
      {
        "<c-s>",
        mode = { "c" },
        function()
        require("flash").toggle()
        end,
        desc = "Toggle Flash Search",
      },
    },
    opts = {},
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "lua" },
      })
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment] 2023-07-02 08:44
Can't reproduce this.

Can you provide a minimal code file and a location in that file that triggers this issue?

Can you also upgrade to the latest nightly to see if the issue is resolved?

There's been a lot of changes in Neovim related to inline extmarks that have been fixed in the meantime

**Closed** 2023-07-03 20:09 UTC
Labels: bug
