### ISSUE TITLE
bug: `,` command not works in `f`command

### ISSUE THREAD

**Issue by chaozwn** [folke/flash.nvim#163] opened 2023-07-16 15:21 UTC
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

macos

### Describe the bug

t works normal in commits  "30a6385c92cc37822eb701c6984d6ba9cbd6f1ab"

### Steps To Reproduce

1. 'f' search a word
2. `;` works normal, `,` not works 

### Expected Behavior

works normal.

### Repro

```Lua
{
    "folke/flash.nvim",
    event = "VeryLazy",
    keys = function() return {} end,
    opts = {}
  },
```

**Comment by chaozwn** [comment] 2023-07-16 15:22
{
    "folke/flash.nvim",
    commit = "30a6385c92cc37822eb701c6984d6ba9cbd6f1ab",
    event = "VeryLazy",
    keys = function() return {} end,
    opts = {}
  }
 works normal.

**Comment by folke** [comment] 2023-07-16 17:19
What does `:nmap ,` say?

I updated flash to never override existing keymaps for , or ;

**Comment by chaozwn** [comment] 2023-07-16 17:23
> What does `:nmap ,` say?
> 
> I updated flash to never override existing keymaps for , or ;

no mappings.
![image](https://github.com/folke/flash.nvim/assets/51357674/b77df5a7-10b2-4d32-8701-7eeb8dab5d51)

**Comment by folke** [comment] 2023-07-16 17:53
I can not reproduce this with the repro below:

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

To test it with the repro, just do `nvim -u repro.lua`

**Comment by folke** [comment] 2023-07-16 17:54
In your regular config, can you first hit `,` and then run `:nmap ,`?

**Comment by medv** [comment] 2023-07-16 23:35
Just spent the last few hours learning about nvim because I couldn't figure out why it works in treesitter mode for contracting the match, yet not in char mode.

No comma is found in any `[verbose] map` (however `;` makes an appearance), nor in `:nmap ,`.
Then I found this issue! Phew. Unfortunately, the repro does not exhibit this issue, so the issue lies elsewhere but unsure how to diagnose.

Thank you for all your hard work folke, would appreciate any pointers but this does not seem like your fault.

**Comment by chaozwn** [comment] 2023-07-17 01:13
> I can not reproduce this with the repro below:
> 
> ```lua
> -- DO NOT change the paths and don't remove the colorscheme
> local root = vim.fn.fnamemodify("./.repro", ":p")
> 
> -- set stdpaths to use .repro
> for _, name in ipairs({ "config", "data", "state", "cache" }) do
>   vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
> end
> 
> -- bootstrap lazy
> local lazypath = root .. "/plugins/lazy.nvim"
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
> end
> vim.opt.runtimepath:prepend(lazypath)
> 
> -- install plugins
> local plugins = {
>   "folke/tokyonight.nvim",
>   { "folke/flash.nvim", opts = {} },
>   -- add any other plugins here
> }
> require("lazy").setup(plugins, {
>   root = root .. "/plugins",
> })
> 
> vim.cmd.colorscheme("tokyonight")
> -- add anything else here
> ```
> 
> To test it with the repro, just do `nvim -u repro.lua`

thanks. It seems like it's not an issue on your end since the function worked fine in your test case. I suggest comparing the differences between several commits until you find the last commit that works correctly.

**Comment by chaozwn** [comment] 2023-07-17 01:45
error from this commit, link: https://github.com/folke/flash.nvim/commit/f4398a6f69ca0f051a0ad9bea0dbc925734f3877
https://github.com/folke/flash.nvim/assets/51357674/5d56bad6-ad4e-4d36-b899-bde51149223f

**Comment by folke** [comment] 2023-07-17 07:14
> In your regular config, can you first hit `,` and then run `:nmap ,`?

Closing this for now, since I can't reproduce this.

As I mentioned I'm pretty confident it's because you have a (possibly lazy) mapping on `,`

**Closed by folke** 2023-07-17 07:14 UTC
Labels: bug

**Comment by chaozwn** [comment] 2023-07-17 07:49
> > In your regular config, can you first hit `,` and then run `:nmap ,`?
> 
> Closing this for now, since I can't reproduce this.
> 
> As I mentioned I'm pretty confident it's because you have a (possibly lazy) mapping on `,`

in `flash/plugins/char.lua` line 104, in my nvim, `vim.g.maplocalleader == ','`, 
so the `,` key is not injected into `keys`. Why do we need to add the condition `if vim.g.mapleader ~= v and vim.g.maplocalleader ~= v then` in this commit `fix(char): never add mappings for mapleader and maplocalleader`?

**Comment by folke** [comment] 2023-07-17 07:51
If you use `,` as your maplocalleader, then you don't want another plugin to override that. If you still want flash top use `,`, then set `maplocalleader` to something else

**Comment by chaozwn** [comment] 2023-07-17 07:52
> If you use `,` as your maplocalleader, then you don't want another plugin to override that. If you still want flash top use `,`, then set `maplocalleader` to something else

thanks,the issue has been resolved.
