### ISSUE TITLE
bug: Dot-repeat blocks standard usage

### ISSUE THREAD

**Issue by idevat** [folke/flash.nvim#40] opened 2023-06-23 15:54 UTC
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

kubuntu

### Describe the bug

Flash.nvim dot-repeat blocks standard dot-repeat usage (see reproducer).

### Steps To Reproduce

1. Let's have a file with simple content:
```
"one.lua"
"two.lua"
"three.lua"
```
2. you are at line 1 and column 1
3. start `/` search: `:/\.lua<cr>`
4. you are on first line on the character `.`
5. remove extension `.lua` by pressing `dt"`
6. press `n` to get to next search result on line 2
7. press `.` to repeat extension remove - ups, it is not removed as expected.

### Expected Behavior

In the step 7, the extension `.lua` on the line 2 should be removed - just as in the case without this plugin.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2023-06-23 16:24
Should be fixed now!

**Closed** 2023-06-23 16:23 UTC
Labels: bug

**Comment by folke** [comment] 2023-07-20 16:16
@vogler what happens in your buffer doesn't look like flash at all. Or at least not with the default settings.

The highlights should stay visible and for `dt` you should see two kinds of highlights.

Your statusline also doesn't seem to change to operator pending mode.

Are you sure there's no other plugin doing this?

**Comment by vogler** [comment] 2023-07-21 06:45
If I disable flash, it also works as it should.
Just tried it again with a config that just loads flash (`NVIM v0.9.0`):
![Recording 2023-07-21 at 08 43 37](https://github.com/folke/flash.nvim/assets/493741/0d521845-140f-40e5-9328-e1dff2e903e4)

**Comment by folke** [comment] 2023-07-21 06:54
@vogler can you open a new issue with a proper repro as instructed in the issue template, with the exact steps to reproduce the issue?

Since it's working as it should for me, I need something reproducible to see what's happening
